"""add webhook_token to workflows

Revision ID: 2c31ef3c1c5a
Revises: aa4ebf687612
Create Date: 2025-09-24 23:41:30.954114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c31ef3c1c5a'
down_revision: Union[str, None] = 'aa4ebf687612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('webhook_token', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workflows_webhook_token'), 'workflows', ['webhook_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_webhook_token'), table_name='workflows')
    op.drop_column('workflows', 'webhook_token')
    # ### end Alembic commands ###
